// <auto-generated />
using EmployeeApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612063007_SeedingDataToEmployeeTable")]
    partial class SeedingDataToEmployeeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeApp.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Age = 25,
                            Gender = "Female",
                            Name = "Mary",
                            Salary = 76000m
                        },
                        new
                        {
                            Id = 1,
                            Age = 25,
                            Gender = "Female",
                            Name = "Mariam",
                            Salary = 76000m
                        },
                        new
                        {
                            Id = 2,
                            Age = 25,
                            Gender = "Female",
                            Name = "Maria",
                            Salary = 45000m
                        },
                        new
                        {
                            Id = 3,
                            Age = 35,
                            Gender = "Male",
                            Name = "Saviour",
                            Salary = 76000m
                        },
                        new
                        {
                            Id = 4,
                            Age = 25,
                            Gender = "Male",
                            Name = "Mahesh",
                            Salary = 96000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
